version: '3.8'

volumes:
  db:

services:
  db:
    image: postgres:15
    container_name: db
    restart: always
    environment:
      - POSTGRES_PASSWORD=root
    volumes:
      - db:/var/lib/postgresql/data
      - ./config/db/init_db.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'
      
  task-api:
    build:
      context: ./task-api
    container_name: task-api
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - db

  task-ui:
    build:
      context: ./task-ui
    container_name: task-ui
    restart: always
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '80:80'
    depends_on:
      - db
