version: '3.8'

volumes:
  db:

services:
  db:
    image: postgres:15
    container_name: db
    restart: always
    environment:
      - POSTGRES_PASSWORD=root
    volumes:
      - db:/var/lib/postgresql/data
      - ./config/db/init_db.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'
