logging:
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS,${TIMEZONE:America/Sao_Paulo}
  level:
    root: ${LOG_LEVEL:info}

server:
  error:
    include-message: always
    include-binding-errors: always
  port: 8080
  servlet:
    context-path: /api/task-manager
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: task-manager
    timezone: ${TIMEZONE:America/Sao_Paulo}
  datasource:
    url: jdbc:postgresql://${DB_HOST:db}:5432/${DB_NAME:task_manager}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:root}
  jmx:
    enabled: false
  jpa:
    open-in-view: true
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  hateoas:
    use-hal-as-default-json-media-type: false
    change-log: classpath:db/changelog/db.changelog-master.yaml
  output:
    ansi:
      enabled: ALWAYS

task-manager:
  auth:
    jwt:
      public-key: ${JWT_PUBLIC_KEY:classpath:certs/public.pem}
      private-key: ${JWT_PRIVATE_KEY:classpath:certs/private.pem}
      lifetime: ${JWT_LIFETIME:15}
    refresh:
      lifetime: ${REFRESH_LIFETIME:10080}
