server:
  error:
    include-message: always
    include-binding-errors: always
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    timezone: ${TIMEZONE:America/Sao_Paulo}
  datasource:
    url: jdbc:h2:mem:taks_manager
    username: sa
    password:
  jmx:
    enabled: false
  jpa:
    open-in-view: true
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: false
  hateoas:
    use-hal-as-default-json-media-type: false

task-manager:
  auth:
    jwt:
      public-key: ${JWT_PUBLIC_KEY:classpath:certs/public.pem}
      private-key: ${JWT_PRIVATE_KEY:classpath:certs/private.pem}
      lifetime: ${JWT_LIFETIME:15}
    refresh:
      lifetime: ${REFRESH_LIFETIME:10080}
